version: '2'
services:
  ons_search:
    build: ./dp-search
    ports:
      - "5000:5000"
    depends_on:
      - elasticsearch
    environment: 
      - ELASTICSEARCH_URL=elasticsearch:9200
  elasticsearch:
    image: elasticsearch:2.4.2
    ports:
     - "9300:9300"
     - "9200:9200"
